#!/bin/bash

set -e

if [[ $DOCKER_TAG == "latest" ]]; then
  KUBECTL_VERSION=$(curl -fs https://storage.googleapis.com/kubernetes-release/release/stable.txt)
  KUBECTL_VERSION=${KUBECTL_VERSION##v}
  AWSCLI_VERSION=latest
  docker build \
    --build-arg KUBECTL_VERSION=$KUBECTL_VERSION \
    --build-arg AWSCLI_VERSION=$AWSCLI_VERSION \
    -f $DOCKERFILE_PATH \
    -t $IMAGE_NAME \
    .
elif [[ $DOCKER_TAG == *"-"* ]]; then
  KUBECTL_VERSION=${DOCKER_TAG##v}
  KUBECTL_VERSION=${KUBECTL_VERSION%%-*}
  AWSCLI_VERSION=${DOCKER_TAG##*-}
  docker build \
    --build-arg KUBECTL_VERSION=$KUBECTL_VERSION \
    --build-arg AWSCLI_VERSION=$AWSCLI_VERSION \
    -f $DOCKERFILE_PATH \
    -t $IMAGE_NAME \
    .
else
  KUBECTL_VERSION=$DOCKER_TAG
  KUBECTL_VERSION=${KUBECTL_VERSION##v}
  docker build \
    --build-arg KUBECTL_VERSION=$KUBECTL_VERSION \
    -f $DOCKERFILE_PATH \
    -t $IMAGE_NAME \
    .
fi
